### ISSUE TITLE
A fixture file could not be found at any of the following paths:

### ISSUE THREAD

**Issue by akashtippa123** [javieraviles/cypress-upload-file-post-form#2]
Code

it('Questionnaires ', function() { 
const yourFiturePath = 'cypress\fixtures\pic\hd4.jpg

cy.get('.upload-button').attachFile(yourFiturePath)
cy.get('.save').click()
}

hd4.jpg file is present in the given path but It's giving me the error
![tile](https://user-images.githubusercontent.com/61974824/94356611-1a457080-00ae-11eb-92e8-a2d7acbfc02d.png)

**Comment by javieraviles** [comment]
the naming in the image file and its path looks so weird to me...

In the code you wrote `cypress\fixtures\pic\hd4.jpg`. 

In the error shows `cypress\fixtures\cypressixtureshd4.jpg`, but looks like there is some strange symbol between `cypress` and `ixtureshd4.jpg` you are missing. Also seems like extension should not be provided since Cypress is trying many extensions for you already attached to the filename.

**Comment by akashtippa123** [comment]
this time I tried this code

t('Questionnaires ', function() {
const yourFiturePath = 'cypress\fixtures\hd4

cy.get('.upload-button').attachFile(yourFiturePath)
cy.get('.save').click()
}

same error I got, if you help me to resolve, it's very helpful for me

**Comment by javieraviles** [comment]
could you attach the error? I am pretty sure it is some issue regarding paths/naming

**Comment by akashtippa123** [comment]
hd4 picture is present in the fixture folder but its telling file found

![screen](https://user-images.githubusercontent.com/61974824/94370204-4099f900-010c-11eb-81d2-7a4df61f02c8.png)

**Comment by akashtippa123** [comment]
Do you have a solution for resolving this issue, please help me, I am trying to resolve this issue from a long  day

**Comment by javieraviles** [comment]
So again, your code is looking for `cypress\fixtures\cypressixtureshd4.jpg`, but I think your file is actually `cypress\fixtures\hd4.jpg`. To me it looks like you are passing the path `cypress\fixtures` twice somehow, resulting into your code thinking your file name is `cypress\fixtures\hd4` where `\f` is some special character (as it looks in your screenshot, red section, top part) which gets omitted in the end -> filename: `cypressixtureshd4` which of course does not exist.

**Comment by akashtippa123** [comment]
No, I am not passing twice path, and there is no special char at all
My code exactly it is only, Really I don't understand from where that special char is coming
it('Questionnaires ', function() {
const yourFiturePath = 'cypress\fixtures\hd4'

cy.get('.upload-button').attachFile(yourFiturePath)
cy.get('.save').click()
}

**Comment by javieraviles** [comment]
Just remove `cypress\fixtures\` from your const `yourFiturePath`:
```
const yourFiturePath = 'hd4'
```

**Comment by akashtippa123** [comment]
Yes I tried as you suggested this time I didn't get any error but still, the photo is not uploaded
it('Questionnaires ', function() {
const yourFiturePath = 'hd4'

cy.get('.upload-button').attachFile(yourFiturePath)
cy.get('.save').click()
}

**Comment by javieraviles** [comment]
well now your problem from the logs is solved. You might have an additional one somewhere else :)

**Comment by akashtippa123** [comment]
yes but still the problem is not resolved, I am trying to resolve this, please let me know you have any solution for this

**Comment by javieraviles** [comment]
as i said, the first problem is solved, you seem to have another one. If you want help, at least show the error :)

**Comment by akashtippa123** [comment]
I don't get any error everything fine Test case passed but the picture not uploaded
![file](https://user-images.githubusercontent.com/61974824/94410077-91edcb00-0194-11eb-8567-9d6e70fecdd9.png)

**Comment by javieraviles** [comment]
i dont see any assertion checking whether the image got uploaded or not. How do you check?

**Comment by akashtippa123** [comment]
After uploading the image it will show "Image uploaded successfully" but Assertion is failed because the picture is not uploaded.
 it('Questionnaires ', function() { 
const yourFiturePath = 'hd4'
cy.get('.upload-button').attachFile(yourFiturePath)
        cy.get('.ant-notification-notice').should('contain.text','Image uploaded successfully')
}
![myfile](https://user-images.githubusercontent.com/61974824/94413702-0e82a880-0199-11eb-9e4d-922c0992fd73.png)

**Comment by javieraviles** [comment]
If you do it manually do you see the notification right after clicking save? no additional steps?

maybe is a matter of waiting?

I think you can debug the test running cypress in a visual mode, can you see the pop up there?

**Comment by akashtippa123** [comment]
Yes I after uploading picture it will show success message

**Comment by javieraviles** [comment]
maybe is a matter of waiting?

**Comment by akashtippa123** [comment]
manually once I select a picture from local, it will upload the picture then immediately it will show the message, no delay after uploaded the picture

**Comment by javieraviles** [comment]
maybe not visually but there is some, try maybe waiting half a second there

**Comment by akashtippa123** [comment]
yes, I tried but it's not working, the picture is not uploading

**Comment by javieraviles** [comment]
why are you so sure of that?

**Comment by akashtippa123** [comment]
I see in the app after executing the script I don't see picture and  pic name
see this form after uploading it should show images, image is not shown on image place holder

![form](https://user-images.githubusercontent.com/61974824/94422851-54456e00-01a5-11eb-9608-6bd04b47b475.png)

**Comment by javieraviles** [comment]
is the command `cy.get('.save').click()` working?

**Comment by akashtippa123** [comment]
yes on this form image is optional

**Comment by javieraviles** [comment]
but you are clicking save right after uploading the image, so probably is moving to some other page and notification is never there?

**Comment by akashtippa123** [comment]
No Scenario is 
1: I will enter all fields
2: then I will upload picture
3: After uploading the picture it will show a success message
4: I will validate the success message
5: then I will click on the Save button

the success message will show before I clicking on the save button

**Comment by javieraviles** [comment]
if you run cypress test in visual mode, can you see how it uploads the image? maybe play with some big waitings so you have time to check

**Comment by akashtippa123** [comment]
i see in Visual mode hd4 is -FILE hd4 nothing happened it  is a DOM snapshot also tried with 10000 waits

**Comment by akashtippa123** [comment]
@javieraviles  what is the cypress version you are using??

**Comment by javieraviles** [comment]
That's exactly what the `package.json` file is meant for, have a look! https://github.com/javieraviles/cypress-upload-file-post-form/blob/master/package.json

**Comment by Janani123-hub** [comment]
I am getting the same error. Please help me out to resolve it. My cypress version is "cypress": "^9.4.1"

**Comment by rgupta8888** [comment]
I am also getting exactly same errors which @akashtippa123 mentioning.

**Comment by shivamGit123** [comment]
I am also getting the same error , my cypress version is 12.3.0

**Comment by id-dan** [comment]
pls try to delete "fixturesFolder" from cypress.config.js/ts, 
https://stackoverflow.com/a/75539482
